/* Design philosophy: Caderno de Campo — clear editorial hierarchy and navigable product decisions. */
import { useMemo, useState } from "react";
import { ArrowRight, Bookmark, Check, ChevronLeft, Compass, ExternalLink, MapPinned, Menu, Minus, Plus, Search, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { toast } from "sonner";

/* Rota de Sol: descoberta mobile-first, coral para avanço e azul-rio para orientação. */
const heroImage = "/manus-storage/bora-piaui-route-sol-hero_14d6511e.jpg";
const riverImage = "/manus-storage/bora-piaui-encontro-das-aguas_774a8581.jpg";
const potteryImage = "/manus-storage/bora-piaui-potter-detail_033e5962.jpg";
const markImage = "/manus-storage/bora-piaui-sun-river-mark_032a7fc1.png";
const sourceVisitBrasil = "https://visitbrasil.com/en/location/teresina/";

type Place = { id: string; title: string; category: "Natureza" | "Cultura" | "Vista"; district: string; text: string; detail: string; route: string; image?: string; accent: string };

const places: Place[] = [
  { id: "rios", title: "Encontro dos Rios", category: "Natureza", district: "Poty Velho", text: "Onde Poti e Parnaíba seguem juntos.", detail: "Um ponto de partida para observar os rios e aproximar natureza, artesanato e território em uma só parada.", route: "https://www.google.com/maps/dir/?api=1&destination=Parque%20Ambiental%20Encontro%20dos%20Rios%2C%20Teresina%2C%20PI", image: riverImage, accent: "#0E6A7D" },
  { id: "ponte", title: "Ponte Estaiada", category: "Vista", district: "Rio Poti", text: "Uma pausa alta para olhar a cidade.", detail: "O complexo da Ponte Estaiada é um símbolo contemporâneo de Teresina e concentra uma vista ampla do Rio Poti e da cidade.", route: "https://www.google.com/maps/dir/?api=1&destination=Mirante%20da%20Ponte%20Estaiada%2C%20Teresina%2C%20PI", accent: "#F05D45" },
  { id: "museu", title: "Museu do Piauí", category: "Cultura", district: "Centro", text: "Histórias do estado em uma parada central.", detail: "Um recorte cultural para quem quer começar a visita entendendo mais do Piauí antes de seguir pela cidade.", route: "https://www.google.com/maps/dir/?api=1&destination=Museu%20do%20Piaui%2C%20Teresina%2C%20PI", accent: "#4A9A6A" },
  { id: "poty", title: "Polo Cerâmico do Poty Velho", category: "Cultura", district: "Poty Velho", text: "Argila, gesto e memória ribeirinha.", detail: "Um lugar para encontrar a cerâmica como expressão de uma prática artesanal ligada à vida às margens dos rios.", route: "https://www.google.com/maps/dir/?api=1&destination=Polo%20Ceramico%20do%20Poty%20Velho%2C%20Teresina%2C%20PI", image: potteryImage, accent: "#B66B3D" },
];

const categories = ["Todos", "Natureza", "Cultura", "Vista"] as const;

export default function Home() {
  const [category, setCategory] = useState<(typeof categories)[number]>("Todos");
  const [query, setQuery] = useState("");
  const [itinerary, setItinerary] = useState<string[]>(["museu", "ponte"]);
  const [selected, setSelected] = useState<Place | null>(null);
  const [plannerOpen, setPlannerOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  const visiblePlaces = useMemo(() => places.filter((place) => (category === "Todos" || place.category === category) && `${place.title} ${place.category} ${place.district}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const plan = itinerary.map((id) => places.find((place) => place.id === id)).filter((place): place is Place => Boolean(place));

  function goTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); setMenuOpen(false); }
  function toggleItinerary(place: Place) { setItinerary((current) => current.includes(place.id) ? current.filter((id) => id !== place.id) : [...current, place.id]); toast.success(itinerary.includes(place.id) ? `${place.title} removido do roteiro.` : `${place.title} entrou no roteiro.`); }
  function clearItinerary() { setItinerary([]); toast.message("Roteiro limpo."); }

  return <div className="min-h-screen bg-[#fffaf1] text-[#183f47]">
    <header className="sticky top-0 z-40 border-b border-[#183f47]/8 bg-[#fffaf1]/92 backdrop-blur-xl">
      <div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <button onClick={() => goTo("inicio")} className="tap flex items-center gap-3" aria-label="Ir ao início"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-2xl bg-[#f05d45] shadow-[0_6px_0_rgba(240,93,69,.16)]"><img src={markImage} alt="Marca Bora Piauí" className="h-9 w-9 object-contain" /></span><span className="text-[1.05rem] font-extrabold tracking-[-0.065em]">bora <span className="text-[#f05d45]">piauí</span></span></button>
        <nav className="hidden items-center gap-7 text-sm font-bold md:flex"><button onClick={() => goTo("explorar")} className="tap hover:text-[#f05d45]">Explorar</button><button onClick={() => goTo("como-funciona")} className="tap hover:text-[#f05d45]">Como funciona</button><a href={sourceVisitBrasil} target="_blank" rel="noreferrer" className="tap hover:text-[#f05d45]">Sobre Teresina</a></nav>
        <div className="flex items-center gap-2"><button onClick={() => setPlannerOpen(true)} className="tap inline-flex h-10 items-center gap-2 rounded-full bg-[#0e6a7d] px-4 text-sm font-extrabold text-white"><Bookmark className="h-4 w-4" /> <span className="hidden sm:inline">Meu roteiro</span><span className="grid h-5 min-w-5 place-items-center rounded-full bg-white/18 px-1 text-[10px]">{plan.length}</span></button><button onClick={() => setMenuOpen((value) => !value)} className="tap grid h-10 w-10 place-items-center rounded-full border border-[#183f47]/12 md:hidden" aria-label="Abrir menu">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>
      </div>
      {menuOpen && <nav className="border-t border-[#183f47]/8 bg-[#fffaf1] px-5 py-4 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-1"><button onClick={() => goTo("explorar")} className="rounded-xl px-3 py-3 text-left text-sm font-bold hover:bg-[#f4ecdd]">Explorar Teresina</button><button onClick={() => goTo("como-funciona")} className="rounded-xl px-3 py-3 text-left text-sm font-bold hover:bg-[#f4ecdd]">Como funciona</button><button onClick={() => setPlannerOpen(true)} className="rounded-xl px-3 py-3 text-left text-sm font-bold hover:bg-[#f4ecdd]">Meu roteiro</button></div></nav>}
    </header>

    <main id="inicio">
      <section className="relative overflow-hidden bg-[#0e6a7d] px-4 pb-10 pt-6 text-white sm:px-6 sm:pb-14 lg:px-8 lg:pt-8">
        <div className="mx-auto grid max-w-7xl items-end gap-8 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="relative z-10 py-7 lg:pb-12 lg:pt-16"><div className="sun-chip inline-flex items-center gap-2 rounded-full bg-[#f05d45] px-4 py-2 text-[11px] font-extrabold uppercase tracking-[0.15em]"><Sparkles className="h-3.5 w-3.5" /> Rota de Sol · Teresina</div><h1 className="display-font mt-7 max-w-xl text-5xl leading-[0.92] tracking-[-0.065em] sm:text-6xl lg:text-7xl">Uma tarde que começa pelo rio.</h1><p className="mt-6 max-w-md text-base leading-7 text-white/78 sm:text-lg">Escolha uma primeira parada, monte seu roteiro e abra a rota quando estiver pronto para sair.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => goTo("explorar")} className="tap inline-flex items-center gap-2 rounded-full bg-[#f05d45] px-5 py-3 text-sm font-extrabold text-white hover:bg-[#ff735e]">Explorar Teresina <ArrowRight className="h-4 w-4" /></button><button onClick={() => setPlannerOpen(true)} className="tap inline-flex items-center gap-2 rounded-full border border-white/28 bg-white/8 px-5 py-3 text-sm font-extrabold text-white hover:bg-white/14">Ver roteiro <Compass className="h-4 w-4" /></button></div></div>
          <div className="relative min-h-[340px] overflow-hidden rounded-[2.25rem] border border-white/18 bg-[#163f48] sm:min-h-[430px]"><img src={heroImage} alt="Ilustração editorial de Teresina entre rios" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#083d4a]/65 via-transparent to-transparent" /><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.17em] text-white/65">Comece aqui</p><p className="mt-1 text-base font-bold">Teresina, entre Poti e Parnaíba</p></div><span className="grid h-12 w-12 place-items-center rounded-full bg-[#fffaf1] text-[#f05d45]"><MapPinned className="h-5 w-5" /></span></div></div>
        </div><div className="route-line absolute bottom-0 left-0 h-[3px] w-full" />
      </section>

      <section id="explorar" className="scroll-mt-20 px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="stop-chip">Parada 01 · escolha</span><h2 className="display-font mt-4 max-w-2xl text-4xl leading-none tracking-[-0.05em] sm:text-5xl">O que combina com seu tempo hoje?</h2></div><button onClick={() => setPlannerOpen(true)} className="tap inline-flex items-center gap-2 self-start rounded-full bg-[#183f47] px-4 py-3 text-sm font-extrabold text-white hover:bg-[#0e6a7d]"><Bookmark className="h-4 w-4" /> {plan.length ? `${plan.length} no roteiro` : "Roteiro vazio"}</button></div>
        <div className="mt-9 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`tap rounded-full px-4 py-2.5 text-sm font-extrabold ${category === item ? "bg-[#f05d45] text-white" : "bg-[#f3ecdf] text-[#48636b] hover:bg-[#eadfcb]"}`}>{item}</button>)}</div><label className="flex h-11 items-center gap-2 rounded-full border border-[#183f47]/12 bg-white px-4 text-[#5e7478] md:w-72"><Search className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por lugar ou tipo" className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-[#93a2a3]" /></label></div>
        <div className="mt-8 lg:grid lg:grid-cols-[minmax(0,1fr)_250px] lg:gap-8"><div className="grid gap-5 lg:grid-cols-12"><article className="place-card relative overflow-hidden rounded-[2rem] bg-[#f2e8d9] lg:col-span-7"><div className="grid min-h-[430px] sm:grid-cols-[0.92fr_1.08fr]"><div className="flex flex-col justify-between p-7 sm:p-9"><div><span className="stop-chip !bg-[#0e6a7d] !text-white before:!bg-[#f05d45]">Parada 01 · natureza</span><h3 className="display-font mt-5 text-4xl leading-[0.92] tracking-[-0.05em]">Encontro<br />dos Rios</h3><p className="mt-4 max-w-xs text-sm leading-6 text-[#48636b]">Onde os rios Poti e Parnaíba seguem juntos — e sua rota pode começar.</p></div><div className="mt-7 flex flex-wrap gap-2"><button onClick={() => setSelected(places[0])} className="tap rounded-full bg-[#183f47] px-4 py-2.5 text-sm font-extrabold text-white">Ver lugar</button><button onClick={() => toggleItinerary(places[0])} className="tap rounded-full border border-[#183f47]/18 px-4 py-2.5 text-sm font-extrabold">{itinerary.includes("rios") ? "No roteiro" : "Adicionar"}</button></div></div><div className="relative min-h-60 overflow-hidden"><img src={riverImage} alt="Ilustração do encontro das águas" className="place-image absolute inset-0 h-full w-full object-cover" /></div></div></article>
          <article className="relative overflow-hidden rounded-[2rem] bg-[#f05d45] p-7 text-white lg:col-span-5"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full border-[28px] border-white/12" /><div className="relative flex h-full min-h-[300px] flex-col justify-between"><div><span className="stop-chip !bg-white/15 !text-white before:!bg-white">Parada 02 · vista</span><h3 className="display-font mt-5 max-w-sm text-4xl leading-[0.94] tracking-[-0.05em]">Olhe Teresina de outro ponto.</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/78">O Mirante da Ponte Estaiada entra como uma pausa de paisagem no roteiro.</p></div><button onClick={() => setSelected(places[1])} className="tap mt-7 inline-flex w-fit items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-extrabold text-[#f05d45]">Conhecer a parada <ArrowRight className="h-4 w-4" /></button></div></article>
          {visiblePlaces.filter((place) => !["rios", "ponte"].includes(place.id)).map((place) => <article key={place.id} className="place-card overflow-hidden rounded-[1.75rem] border border-[#183f47]/10 bg-white lg:col-span-6"><div className="grid min-h-[300px] grid-cols-[0.9fr_1.1fr]"><div className="relative overflow-hidden bg-[#efe5d4]">{place.image ? <img src={place.image} alt={`Ilustração de ${place.title}`} className="place-image absolute inset-0 h-full w-full object-cover" /> : <div className="soft-grid grid h-full place-items-center"><Compass className="h-14 w-14 text-[#4a9a6a]" /></div>}</div><div className="flex flex-col justify-between p-6"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.15em]" style={{ color: place.accent }}>{place.category} · {place.district}</p><h3 className="display-font mt-3 text-3xl leading-[0.95] tracking-[-0.045em]">{place.title}</h3><p className="mt-3 text-sm leading-6 text-[#5b7074]">{place.text}</p></div><div className="mt-5 flex gap-2"><button onClick={() => setSelected(place)} className="tap rounded-full bg-[#eff4f2] px-3.5 py-2 text-xs font-extrabold text-[#183f47]">Detalhes</button><button onClick={() => toggleItinerary(place)} className="tap grid h-9 w-9 place-items-center rounded-full border border-[#183f47]/12" aria-label={`Adicionar ${place.title} ao roteiro`}>{itinerary.includes(place.id) ? <Check className="h-4 w-4 text-[#4a9a6a]" /> : <Plus className="h-4 w-4" />}</button></div></div></div></article>)}
        </div>{visiblePlaces.length === 0 && <div className="mt-8 rounded-[1.5rem] border border-dashed border-[#183f47]/20 p-10 text-center"><SlidersHorizontal className="mx-auto h-7 w-7 text-[#f05d45]" /><p className="mt-3 font-bold">Nenhuma parada encontrada.</p><button onClick={() => { setCategory("Todos"); setQuery(""); }} className="mt-4 text-sm font-extrabold text-[#0e6a7d]">Limpar filtros</button></div>}<aside className="mt-6 hidden lg:block"><div className="route-companion sticky top-24 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#ff9a86]">Seu caminho</p><p className="display-font mt-2 text-3xl leading-none">{plan.length ? `${plan.length} parada${plan.length > 1 ? "s" : ""}` : "Comece daqui"}</p><div className="mt-6 space-y-4">{plan.length ? plan.slice(0, 3).map((place, index) => <div key={place.id} className="route-stop"><p className="text-[10px] font-extrabold text-white/45">0{index + 1}</p><p className="mt-0.5 text-sm font-extrabold leading-5">{place.title}</p></div>) : <div className="route-stop"><p className="text-sm font-bold leading-5 text-white/72">Adicione uma parada para ver seu caminho ganhar forma.</p></div>}</div><button onClick={() => setPlannerOpen(true)} className="tap mt-7 w-full rounded-full bg-[#f05d45] px-4 py-3 text-sm font-extrabold text-white">Abrir meu roteiro</button></div></aside></div>
      </div></section>

      <section id="como-funciona" className="bg-[#183f47] px-4 py-14 text-white sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.86fr_1.14fr]"><div><span className="stop-chip !bg-[#f05d45] !text-white before:!bg-white">Parada 03 · siga</span><h2 className="display-font mt-4 text-5xl leading-[0.94] tracking-[-0.055em]">Menos lista. Mais caminho.</h2><p className="mt-5 max-w-md text-base leading-7 text-white/72">Junte poucas paradas, escolha um ritmo e decida qual é a próxima rota que faz sentido para você.</p></div><div className="grid gap-3 sm:grid-cols-3">{[{ n: "01", title: "Descubra", text: "Filtre por natureza, cultura ou vista." }, { n: "02", title: "Guarde", text: "Adicione somente o que faz sentido." }, { n: "03", title: "Vá", text: "Abra a rota no Google Maps." }].map((step) => <div key={step.n} className="rounded-[1.5rem] bg-white/8 p-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f05d45] text-xs font-extrabold">{step.n}</span><h3 className="mt-8 text-lg font-extrabold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-white/66">{step.text}</p></div>)}</div></div>
      </section>
    </main>

    {selected && <div className="fixed inset-0 z-50 flex items-end bg-[#112f36]/55 p-0 backdrop-blur-[2px] sm:items-center sm:justify-center sm:p-6" role="dialog" aria-modal="true" aria-label={`Detalhes de ${selected.title}`}><div className="w-full max-w-xl overflow-hidden rounded-t-[2rem] bg-[#fffaf1] sm:rounded-[2rem]"><div className="flex items-center justify-between p-5 sm:p-6"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.15em]" style={{ color: selected.accent }}>{selected.category} · {selected.district}</p><h2 className="display-font mt-2 text-3xl tracking-[-0.05em]">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="tap grid h-10 w-10 place-items-center rounded-full bg-[#f3ecdf]" aria-label="Fechar detalhes"><X className="h-5 w-5" /></button></div><div className="px-5 pb-6 sm:px-6 sm:pb-7">{selected.image && <img src={selected.image} alt="" className="mb-5 h-44 w-full rounded-[1.25rem] object-cover" />}<p className="text-base leading-7 text-[#526a70]">{selected.detail}</p><p className="mt-4 text-xs leading-5 text-[#718489]">Conteúdo de referência para o protótipo. Confirme condições de visita antes de sair.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={() => toggleItinerary(selected)} className="tap inline-flex justify-center gap-2 rounded-full bg-[#183f47] px-4 py-3 text-sm font-extrabold text-white">{itinerary.includes(selected.id) ? <Minus className="h-4 w-4" /> : <Plus className="h-4 w-4" />}{itinerary.includes(selected.id) ? "Remover do roteiro" : "Adicionar ao roteiro"}</button><a href={selected.route} target="_blank" rel="noopener noreferrer" className="tap inline-flex justify-center gap-2 rounded-full bg-[#f05d45] px-4 py-3 text-sm font-extrabold text-white">Abrir rota <ExternalLink className="h-4 w-4" /></a></div></div></div></div>}
    {plannerOpen && <div className="fixed inset-0 z-50 flex justify-end bg-[#112f36]/45 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-label="Meu roteiro"><div className="flex h-full w-full max-w-md flex-col bg-[#fffaf1] shadow-2xl"><div className="flex items-center justify-between border-b border-[#183f47]/10 p-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[#f05d45]">Meu roteiro</p><h2 className="display-font mt-1 text-3xl tracking-[-0.05em]">Uma tarde em Teresina</h2></div><button onClick={() => setPlannerOpen(false)} className="tap grid h-10 w-10 place-items-center rounded-full bg-[#f3ecdf]" aria-label="Fechar roteiro"><X className="h-5 w-5" /></button></div><div className="flex-1 overflow-y-auto p-5"><div className="rounded-[1.5rem] bg-[#0e6a7d] p-5 text-white"><p className="text-sm font-bold">{plan.length ? `${plan.length} parada${plan.length > 1 ? "s" : ""} escolhida${plan.length > 1 ? "s" : ""}` : "Seu roteiro está vazio"}</p><p className="mt-1 text-sm leading-6 text-white/72">Adicione lugares enquanto explora. Você pode remover qualquer um aqui.</p></div>{plan.length ? <ol className="mt-6 space-y-3">{plan.map((place, index) => <li key={place.id} className="flex gap-3 rounded-[1.25rem] border border-[#183f47]/10 bg-white p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#f05d45] text-xs font-extrabold text-white">{index + 1}</span><div className="min-w-0 flex-1"><p className="font-extrabold">{place.title}</p><p className="mt-0.5 text-xs font-bold text-[#5e7478]">{place.category} · {place.district}</p></div><button onClick={() => toggleItinerary(place)} className="tap grid h-8 w-8 place-items-center rounded-full bg-[#f4ecdf]" aria-label={`Remover ${place.title}`}><Minus className="h-4 w-4" /></button></li>)}</ol> : <div className="mt-6 rounded-[1.5rem] border border-dashed border-[#183f47]/18 p-8 text-center"><Compass className="mx-auto h-7 w-7 text-[#f05d45]" /><p className="mt-3 text-sm font-bold">Escolha uma primeira parada para começar.</p></div>}</div><div className="border-t border-[#183f47]/10 p-5"><div className="flex gap-3"><button onClick={() => goTo("explorar")} className="tap flex-1 rounded-full bg-[#183f47] px-4 py-3 text-sm font-extrabold text-white">Explorar</button><button onClick={clearItinerary} disabled={!plan.length} className="tap rounded-full border border-[#183f47]/15 px-4 py-3 text-sm font-extrabold disabled:cursor-not-allowed disabled:opacity-35">Limpar</button></div></div></div></div>}
    <footer className="border-t border-[#183f47]/8 px-4 py-8 text-xs text-[#6b7d80] sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 sm:flex-row"><p>Bora Piauí · Protótipo navegável de Teresina.</p><p>Referência de conteúdo: <a href={sourceVisitBrasil} target="_blank" rel="noreferrer" className="font-extrabold text-[#0e6a7d] underline underline-offset-2">Visit Brasil</a> · consulta em 20 ago. 2026.</p></div></footer>
  </div>;
}
