import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, ChefHat, CircleDot, GlassWater, MapPinned, Sparkles } from "lucide-react";
import { Link } from "wouter";

export const stories = [
  {
    title: "Cajuína",
    type: "Bebida e técnica",
    icon: GlassWater,
    image: "/manus-storage/sabores-cajuina-editorial_16ca691f.jpg",
    source: "INPI · Indicação Geográfica da Cajuína do Piauí",
    url: "https://www.gov.br/inpi/pt-br/servicos/indicacoes-geograficas/arquivos/fichas-tecnicas-de-indicacoes-geograficas/Piau.pdf",
    text: "Nesta trilha, a cajuína é apresentada como bebida associada ao trabalho de transformação do caju. A ficha técnica da Indicação Geográfica “Piauí”, do INPI, descreve sua consolidação como bebida tradicional e conhecida em todo o estado. O recorte privilegia produto, técnica e circulação, sem repetir aqui o enquadramento patrimonial da seção própria.",
    notes: ["A ficha do INPI é usada como referência produtiva e territorial.", "A indicação geográfica relaciona produto e território, não uma marca específica.", "O reconhecimento patrimonial da prática permanece contextualizado em Patrimônios."],
  },
  {
    title: "Bomba",
    type: "Memória urbana de Teresina",
    icon: CircleDot,
    image: "/manus-storage/bomba-g1_223f14dd.jpg",
    source: "g1 Piauí · relato jornalístico",
    url: "https://g1.globo.com/pi/piaui/noticia/2022/02/10/conheca-marlene-ferreira-piauiense-apontada-como-a-criadora-da-bomba-salgado-pivo-de-discussao-no-twitter.ghtml",
    text: "A Bomba, salgado recheado que marca balcões e intervalos em Teresina, entra aqui como memória urbana. Em reportagem do g1 baseada no relato da família de Marlene Ferreira, sua origem é atribuída a uma sobra de massa de esfirra recheada com presunto e queijo, em meados dos anos 1980. Não é um bem oficialmente registrado: esta é uma narrativa jornalística de origem, identificada como tal.",
    notes: ["A narrativa de autoria é atribuída à empresária Marlene Ferreira.", "O texto usa fonte jornalística, não registro patrimonial oficial.", "A categoria privilegia contexto e técnica, não recomenda estabelecimentos ou preços."],
  },
];

export const gallery = [
  { title: "Cajuína", region: "Centro-Norte", kind: "Produto e Indicação Geográfica", description: "A galeria apresenta a cajuína pela relação entre produto, técnica e território. O recorte regional é editorial e não delimita os locais de produção.", image: "/manus-storage/sabores-cajuina-editorial_16ca691f.jpg", imageNote: "Imagem editorial do preparo", imageCredit: "Visual editorial do protótipo", source: "INPI · Indicação Geográfica da Cajuína do Piauí", url: "https://www.gov.br/inpi/pt-br/servicos/indicacoes-geograficas/arquivos/fichas-tecnicas-de-indicacoes-geograficas/Piau.pdf" },
  { title: "Bomba", region: "Teresina", kind: "Memória urbana", description: "O salgado entra como narrativa da cidade, com origem relatada em fonte jornalística. Não representa registro cultural oficial.", image: "/manus-storage/bomba-g1_223f14dd.jpg", imageNote: "Imagem de referência do preparo", imageCredit: "Imagem: g1 Piauí", source: "g1 Piauí · relato jornalístico", url: "https://g1.globo.com/pi/piaui/noticia/2022/02/10/conheca-marlene-ferreira-piauiense-apontada-como-a-criadora-da-bomba-salgado-pivo-de-discussao-no-twitter.ghtml" },
  { title: "Maria Isabel", region: "Interior e sertões", kind: "Referência visual", description: "", image: "/manus-storage/maria-isabel-referencia_266a96ca.jpeg", imageNote: "Imagem de referência do preparo", imageCredit: "", source: null, url: null },
  { title: "Paçoca de carne de sol", region: "Interior e sertões", kind: "Leitura de técnica", description: "O pilão, a carne e a farinha orientam esta ficha de pesquisa. A receita publicada em Receitas do Piauí descreve uma mistura tipicamente piauiense; o recorte territorial serve à navegação e não declara exclusividade de origem.", image: "/manus-storage/pacoca-carne-sol-turismo-piaui_80dc0c6c.jpeg", imageNote: "Imagem de referência do preparo", imageCredit: "Imagem: Turismo Piauí", source: "Rede Clube · Receitas do Piauí", url: "https://redeglobo.globo.com/pi/redeclube/receitas-do-piaui/noticia/descubra-o-segredo-da-tradicional-receita-de-pacoca-com-carne-de-sol.ghtml" },
];

export const regions = ["Todos", "Teresina", "Centro-Norte", "Interior e sertões"] as const;
export type FlavorRegion = (typeof regions)[number];
export function filterGallery(region: FlavorRegion) { return region === "Todos" ? gallery : gallery.filter((item) => item.region === region); }

function Topbar() {
  return <header className="sticky top-0 z-40 border-b border-[#3C482D]/10 bg-[#F5ECD8]/95 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-extrabold text-[#3C482D] hover:text-[#B9572D]"><ArrowLeft className="h-4 w-4" /> Voltar ao atlas</Link><nav className="flex items-center gap-3 text-xs font-extrabold sm:gap-5 sm:text-sm"><Link href="/patrimonios" className="hidden hover:text-[#B9572D] sm:inline">Patrimônios</Link><Link href="/sabores" className="hidden text-[#B9572D] sm:inline">Sabores</Link><Link href="/dados" className="hidden hover:text-[#B9572D] sm:inline">Dados</Link><Link href="/agenda" className="hover:text-[#B9572D]">Agenda</Link><Link href="/parceiros" className="rounded-full bg-[#3C482D] px-3 py-2 text-white hover:bg-[#566B37]">Parceiros</Link></nav></div></header>;
}

export default function SaboresPage() {
  const [activeRegion, setActiveRegion] = useState<FlavorRegion>("Todos");
  const filteredGallery = useMemo(() => filterGallery(activeRegion), [activeRegion]);
  return <div className="min-h-screen bg-[#F5ECD8] text-[#2E3222]"><Topbar /><main>
    <section className="border-b border-[#3C482D]/10 px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#B9572D] px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.16em] text-white"><ChefHat className="h-3.5 w-3.5" /> Cozinha como narrativa</span><h1 className="display-font mt-6 text-5xl leading-[.92] tracking-[-.06em] sm:text-6xl">Sabores não são só pratos típicos.</h1></div><p className="self-end text-base leading-8 text-[#566457] sm:text-lg">Esta trilha apresenta preparos como histórias: matéria-prima, técnica, relações de trabalho, circulação e memória. Cada entrada explica o tipo de fonte usado, para diferenciar um reconhecimento oficial de um relato jornalístico.</p></div></section>
    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl space-y-7">{stories.map((story) => { const Icon = story.icon; return <article key={story.title} className="grid overflow-hidden rounded-[2rem] border border-[#3C482D]/10 bg-[#FFFDF6] lg:grid-cols-[.62fr_1.38fr]"><div className="relative min-h-[280px] overflow-hidden"><img src={story.image} alt={`Preparação de ${story.title}`} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#273020]/95 via-[#273020]/35 to-[#273020]/20" /><div className="relative z-10 flex min-h-[280px] flex-col justify-between p-7 text-white"><Icon className="h-8 w-8 text-[#F2D270]" /><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-white/75">{story.type}</p><h2 className="display-font mt-2 text-5xl tracking-[-.06em]">{story.title}</h2></div></div></div><div className="p-7 sm:p-9"><p className="max-w-3xl text-base leading-8 text-[#566457]">{story.text}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{story.notes.map((note) => <div key={note} className="border-t-2 border-[#B9572D] pt-3 text-sm font-semibold leading-5 text-[#465039]">{note}</div>)}</div><a href={story.url} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-[#B9572D] hover:underline">{story.source} <ArrowUpRight className="h-4 w-4" /></a></div></article>; })}</div></section>
    <section className="border-y border-[#3C482D]/10 bg-[#E9DCC0] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-7 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><span className="inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#B9572D]"><MapPinned className="h-3.5 w-3.5" /> Galeria territorial</span><h2 className="display-font mt-3 text-4xl tracking-[-.05em] sm:text-5xl">Sabores por recorte de região.</h2></div><p className="border-l border-[#3C482D]/15 pl-5 text-sm font-semibold leading-6 text-[#566B37]">O filtro organiza as narrativas por recorte editorial de pesquisa. Ele não declara origem exclusiva de um preparo nem substitui estudos culinários ou registros culturais.</p></div><div className="mt-8 flex flex-wrap gap-2">{regions.map((region) => <button key={region} type="button" onClick={() => setActiveRegion(region)} className={`rounded-full border px-4 py-2 text-xs font-extrabold transition-colors ${activeRegion === region ? "border-[#B9572D] bg-[#B9572D] text-white" : "border-[#3C482D]/15 bg-[#FFFDF6] text-[#3C482D] hover:border-[#B9572D] hover:text-[#B9572D]"}`}>{region}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{filteredGallery.map((item) => <article key={item.title} className="overflow-hidden rounded-[1.5rem] border border-[#3C482D]/10 bg-[#FFFDF6]"><div className="relative"><img src={item.image} alt={`Imagem de referência de ${item.title}`} className="h-52 w-full object-cover" /><span className="absolute bottom-0 left-0 right-0 bg-[#2E3222]/80 px-3 py-2 text-[9px] font-extrabold uppercase tracking-[.1em] text-white">{item.imageNote}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-[#E9DCC0] px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#566B37]">{item.region}</span><Sparkles className="h-4 w-4 shrink-0 text-[#B9572D]" /></div><h3 className="display-font mt-5 text-3xl tracking-[-.04em]">{item.title}</h3><p className="mt-2 text-xs font-extrabold uppercase tracking-[.12em] text-[#B9572D]">{item.kind}</p><p className="mt-4 text-sm leading-6 text-[#566457]">{item.description}</p><p className="mt-4 text-[10px] font-bold uppercase tracking-[.1em] text-[#7A6A50]">{item.imageCredit}</p>{item.url ? <a href={item.url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold text-[#B9572D] hover:underline">{item.source} <ArrowUpRight className="h-4 w-4" /></a> : item.source ? <p className="mt-4 text-xs font-bold text-[#566B37]">{item.source}</p> : null}</div></article>)}</div>{filteredGallery.length === 0 && <div className="mt-8 rounded-[1.5rem] border border-dashed border-[#3C482D]/25 bg-[#FFFDF6]/70 p-8 text-sm font-semibold text-[#566457]">Ainda não há uma narrativa editorial publicada para este recorte.</div>}</div></section>
    <section className="bg-[#3C482D] px-4 py-14 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#D9A640]">Próxima camada editorial</p><h2 className="display-font mt-3 text-4xl tracking-[-.05em]">Outros sabores entram quando houver fonte clara e contexto suficiente.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-white/72">Folclores, história do estado e novas práticas alimentares permanecem previstos para uma etapa posterior, sem preencher lacunas com informações presumidas.</p></div></section>
  </main></div>;
}
